version: "3.4"

services:
  node:
    build:
      context: "node/"
    image: node-app
    env_file:
      - "./node/.env"
    ports:
      - 8090:3000

  angular:
    build:
      context: "angular/"
    image: angular-app
    env_file:
      - "./angular/.env"
    ports:
      - 8082:3000

  react:
    build:
      context: "react/"
    image: react-app
    env_file:
      - "./react/.env"
    ports:
      - 8083:3000

  reacttypescript:
    build:
      context: "reacttypescript/"
    image: reacttypescript-app
    env_file:
      - "./reacttypescript/.env"
    ports:
      - 8084:3000

  vue:
    build:
      context: "vue/"
    image: vue-app
    env_file:
      - "./vue/.env"
    ports:
      - 8085:3000

  vuetypescript:
    build:
      context: "vuetypescript/"
    image: vue-app
    env_file:
      - "./vuetypescript/.env"
    ports:
      - 8086:3000
